name: Rebase Downstream on Upstream
# This workflow keeps a downstream branch up to date by rebasing it onto an
# upstream branch and opening/updating a PR with the rebased result.
#
# Why rebase?
# - Keeps a linear history on the downstream branch, making it easier to read.
# - Ensures downstream changes are replayed on top of upstream, reducing merge
#   noise.
#
# How it works at a glance:
# 1) Checkout downstream branch with full history (fetch-depth: 0)
# 2) Add and fetch the upstream remote
# 3) Detect if upstream is already contained in downstream; if yes, exit early
# 4) Rebase downstream onto upstream
# 5) Push rebased history to a temporary branch (force-with-lease)
# 6) Create or update a PR from the temporary branch into downstream using GH CLI

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:
    inputs:
      downstream_branch:
        description: Downstream branch to rebase (destination)
        required: false
        default: main
      upstream_branch:
        description: Upstream branch to rebase onto (source)
        required: false
        default: main

permissions:
  contents: write
  pull-requests: write
<<<<<<< HEAD
  issues: write
=======

>>>>>>> b0b052a (update workflow)

jobs:
  rebase:
    runs-on: ubuntu-latest
    env:
      DOWNSTREAM_BRANCH: ${{ inputs.downstream_branch || 'main' }}
      UPSTREAM_BRANCH: ${{ inputs.upstream_branch || 'main' }}

    steps:
      # 1️⃣ Checkout downstream repository
      - name: Checkout downstream repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DOWNSTREAM_BRANCH }}
          # Fetch the full commit history so `git rebase` has everything it needs.
          # Shallow clones (fetch-depth: 1) can cause rebase failures or surprises.
          fetch-depth: 0
          # Keep the token available for pushes made later in this workflow.
          persist-credentials: true

      # 2️⃣ Set up Git
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 2.1️⃣ Enable rerere (reuse recorded resolutions)
      # rerere records how you resolve specific conflict hunks, and will
      # automatically re-apply the same resolution the next time the exact
      # conflict occurs. This helps make recurring rebases non-interactive.
      - name: Enable rerere (reuse recorded resolutions)
        run: |
          git config rerere.enabled true
          git config rerere.autoUpdate true

      # 2.2️⃣ Restore rerere cache (persists conflict resolutions across runs)
      - name: Restore rerere cache
        uses: actions/cache/restore@v4
        with:
          path: .git/rr-cache
          key: rerere-${{ github.repository }}-${{ env.DOWNSTREAM_BRANCH }}-${{ env.UPSTREAM_BRANCH }}
          restore-keys: |
            rerere-${{ github.repository }}-


      # 3️⃣ Add upstream remote and fetch
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/briangallagher/test-upstream
          git fetch upstream

      # 4️⃣ Check for upstream changes
      - name: Check for upstream commits
        id: check_upstream
        run: |
          # Determine whether the upstream branch tip is already included in
          # the downstream branch. If yes, we avoid unnecessary rebase.
          git fetch upstream "$UPSTREAM_BRANCH"
          UPSTREAM_COMMIT=$(git rev-parse "upstream/$UPSTREAM_BRANCH")
          LOCAL_COMMIT=$(git rev-parse "$DOWNSTREAM_BRANCH")
          if git merge-base --is-ancestor $UPSTREAM_COMMIT $LOCAL_COMMIT; then
            echo "up_to_date=true" >> $GITHUB_OUTPUT
            echo "✅ Already up to date. Nothing to rebase."
          else
            echo "up_to_date=false" >> $GITHUB_OUTPUT
          fi

      # 5️⃣ Rebase onto upstream/main if needed
      - name: Rebase onto upstream branch
        if: steps.check_upstream.outputs.up_to_date == 'false'
        id: rebase
        run: |
          git checkout "$DOWNSTREAM_BRANCH"
          if git rebase "upstream/$UPSTREAM_BRANCH"; then
              echo "rebase_status=success" >> $GITHUB_OUTPUT
          else
              git rebase --abort
              echo "rebase_status=failure" >> $GITHUB_OUTPUT
              echo "Rebase attempted and failed."
          fi

      # 5.1️⃣ Ensure rerere cache directory exists before saving
      - name: Ensure rerere cache directory
        if: always()
        run: mkdir -p .git/rr-cache

      # 5.2️⃣ Save rerere cache to speed up future conflict resolutions
      - name: Save rerere cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: .git/rr-cache
          key: rerere-${{ github.run_id }}

      # 6️⃣ Push to temporary branch for PR
      - name: Push rebased branch
        if: steps.check_upstream.outputs.up_to_date == 'false' && steps.rebase.outputs.rebase_status == 'success'
<<<<<<< HEAD
        run: |
          # Push the rebased downstream branch to a temporary branch that will
          # back the pull request. Use force-with-lease for safety to avoid
          # overwriting remote updates made by others unexpectedly.
          git push origin "$DOWNSTREAM_BRANCH":rebase/"${DOWNSTREAM_BRANCH}"-tmp --force-with-lease
=======
        run: git push origin "$DOWNSTREAM_BRANCH":rebase/"${DOWNSTREAM_BRANCH}"-tmp --force
>>>>>>> b0b052a (update workflow)

      # 7️⃣ Create or update PR for successful rebase
      - name: Create or update PR
        if: steps.check_upstream.outputs.up_to_date == 'false' && steps.rebase.outputs.rebase_status == 'success'
<<<<<<< HEAD
        env:
          # GitHub CLI uses GH_TOKEN for auth; the default token has repo-scoped permissions.
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use GitHub CLI to create or update a PR from the temporary branch.
          # This works reliably when the branch was already pushed by earlier steps.
          set -euo pipefail

          HEAD_BRANCH="rebase/${DOWNSTREAM_BRANCH}-tmp"
          BASE_BRANCH="${DOWNSTREAM_BRANCH}"
          TITLE="Rebase ${DOWNSTREAM_BRANCH} onto upstream/${UPSTREAM_BRANCH}"
          BODY="Automatic rebase of downstream ${DOWNSTREAM_BRANCH} onto upstream/${UPSTREAM_BRANCH}."
          LABEL="automated-rebase"

          # Use gh CLI against the exact repository to avoid context issues
          REPO_REF="${GITHUB_REPOSITORY}"

          # If a PR already exists for this head branch, update it; otherwise create it
          if gh pr view "$HEAD_BRANCH" --repo "$REPO_REF" >/dev/null 2>&1; then
            echo "Updating existing PR for $HEAD_BRANCH"
            gh pr edit "$HEAD_BRANCH" --repo "$REPO_REF" \
              --title "$TITLE" \
              --body "$BODY"
          else
            echo "Creating PR from $HEAD_BRANCH to $BASE_BRANCH"
            # If there are no differences or permissions restrict creation, this will fail and stop the job.
            gh pr create --repo "$REPO_REF" \
              --base "$BASE_BRANCH" \
              --head "$HEAD_BRANCH" \
              --title "$TITLE" \
              --body "$BODY"
          fi

          # Add label to the PR; failures will stop the job
          gh pr edit "$HEAD_BRANCH" --repo "$REPO_REF" --add-label "$LABEL"
=======
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Rebase ${{ env.DOWNSTREAM_BRANCH }} onto upstream/${{ env.UPSTREAM_BRANCH }}"
          commit-message: "Rebased ${{ env.DOWNSTREAM_BRANCH }} onto upstream/${{ env.UPSTREAM_BRANCH }}"
          base: ${{ env.DOWNSTREAM_BRANCH }}
          head: rebase/${{ env.DOWNSTREAM_BRANCH }}-tmp
          body: "Automatic rebase of downstream ${{ env.DOWNSTREAM_BRANCH }} onto upstream/${{ env.UPSTREAM_BRANCH }}."
          draft: false
          labels: automated-rebase
>>>>>>> b0b052a (update workflow)

      # 8️⃣ Fail workflow if rebase failed
      - name: Fail workflow if rebase failed
        if: steps.check_upstream.outputs.up_to_date == 'false' && steps.rebase.outputs.rebase_status == 'failure'
        run: exit 1

